version: '3.7'

services: 
  seq:
    container_name: seq
    image: datalust/seq:latest
    restart: unless-stopped
    ports: 
      - 5341:80
    volumes: 
      - logs:/data
    environment:
      ACCEPT_EULA: Y

  main:
    container_name: vrs-module-main
    build: src/Module.Main
    command: [ "python", "main.py" ]
    environment:
      CAM_IP: 'http://81.200.4.117/mjpg/video.mjpg'
      FGN_ENABLED: 'True'
      VRN_ENABLED: 'True'
      DIDN_ENABLED: 'True'
      SEQ_ADDRESS: 'http://seq:5341/'
      FGN_ADDRESS: 'fgn:8500'
      VRN_ADDRESS: 'vrn:8500'
      DIDN_ADDRESS: 'didn:8500'
    depends_on:
      - seq
      - didn
      - fgn
      - vrn

  fgn:
    container_name: vrs-fgn
    build: src/Module.FGN/
    ports:
      - '8520:8500'
    environment:
      MODEL_NAME: fgn

  didn:
    container_name: vrs-didn
    build: src/Module.DIDN/
    ports:
      - '8510:8500'
    environment: 
      MODEL_NAME: didn

  vrn:
    container_name: vrs-vrn
    build: src/Module.VRN/
    command: ["--model_config_file=/models/models.config"]
    ports:
      - '8500:8500'
    environment: 
      MODEL_NAME: vrn
      MODEL_BASE_NAME: vgg_base

volumes: 
  logs: